/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *pClock = (uint32_t *) 0x40021018; // RCC_APB2ENR
	uint32_t *pPortAMode = (uint32_t *) 0x40010800; // GPIOA_CRL
	uint32_t *pPortAOutput = (uint32_t *) 0x4001080C; // GPIOA_ODR

	// turn on clock
	*pClock |= (1 << 2);
	//clear bits
	*pPortAMode &= ~(0xF << 20);   // Clear bits 23:20 (PA5)
	*pPortAMode |=  (0x2 << 20);  // 0x2 = 0b0010 (output push-pull)
	// set bits
	*pPortAOutput |= (0x20);  // turn on

	//*pPortAOutput |=  0x20;


    /* Loop forever */
	for(;;);
}
