/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

typedef struct {

}RCC_APB2ENR_t;

int main(void)
{
	uint32_t *pClock = (uint32_t *)0x40021018;
	uint32_t *pPortAMode = (uint32_t *)0x40010800;
	uint32_t *pPortAOutput = (uint32_t *)0x4001080C;
	uint32_t *pPortAInput = (uint32_t *)0x40010808;

	*pClock |= (1 << 2); // turn on the clock;

	*pPortAMode &= ~(15 << 20); // clear bits for pin 5

	*pPortAMode &= ~(0xF << 0); // 0xF is 15 in hex this clear bits for pin 0

	*pPortAMode |= (1 << 21); // turn on output mode for pin 5;

	*pPortAMode |= (1 << 3); // turn on input mode for pin 0;



    /* Loop forever */
	while(1){
			if (*pPortAInput & 1){
				*pPortAOutput |= (1 << 5 ); // turn on led at pin 5
			}
			else {
				*pPortAOutput &= ~(1 << 5); // turn of led
			}
		}
}
